include:
  - ./adguard/adguard.yaml
  - ./vaultwarden/vaultwarden.yaml
  - ./cloudflared-tunnel/cloudflared-tunnel.yaml
  - ./caddy/caddy.yaml
  - ./syncthing/syncthing.yaml
  - ./uptime-kuma/uptime-kuma.yaml
  - ./filebrowser/filebrowser.yaml
  - ./navidrome/navidrome.yaml
  - ./postgres/postgres.yaml

networks:
  homelab_net:
    name: homelab_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24 #Using this subnet to avoid IP address conflicts with LAN.
